name: Generate Documentation

on:
  push:
    paths:
      - 'snippets/**/*.json'
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate Documentation and Index
        run: |
          chmod +x ./generate-docs.sh
          ./generate-docs.sh
          
      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md index.json
          git diff --quiet && git diff --staged --quiet || git commit -m "docs: update snippets documentation and index"
          git push