name: Generate Documentation

on:
  push:
    paths:
      - 'snippets/**/*.json'
  workflow_dispatch:

jobs:
  test-and-generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          
      - name: Check for duplicate keywords
        run: |
          chmod +x ./test-snippets.sh
          ./test-snippets.sh
          
      - name: Generate Documentation and Index
        if: success()
        run: |
          chmod +x ./generate-docs.sh
          ./generate-docs.sh
          
      - uses: stefanzweifel/git-auto-commit-action@v5
        if: success()
        with:
          commit_message: "docs: update snippets documentation and index"
          file_pattern: 'README.md index.json'